# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Maguire Lab
email: finlay.maguire@dal.ca
description: > # this means to ignore newlines until "baseurl:"
  Website of the Maguire Lab at Dalhousie.
domain: maguire-lab.github.io
baseurl: "/maguire-lab.github.io/"
url: "https://maguire-lab.github.io"

include:
  - .htaccess
  - _layouts
  - _includes
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge


lsi: false
safe: true
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
